export const PROFESSIONAL_TITLES = [
  "Infectious Disease Physician",
  "Clinical Pharmacist",
  "Microbiologist",
  "Infection Prevention Specialist",
  "Hospital administrator",
  "Other, please specify",
] as const;

export const EXPERIENCE_LEVELS = [
  "0-1 years",
  "2-5 years",
  "6-10 years",
  "11-15 years",
  "16-20 years",
  "20+ years",
] as const;

export const INSTITUTIONS = [
  "Adventist Health Bakersfield",
  "Alton Memorial Hospital",
  "Amala Institute of Medical Sciences Thrissur Kerala India",
  "Aspirus Rhinelander Hospital",
  "Aspirus Wisconsin Rapids Hospital",
  "Atrium Health",
  "Atrium Health Carolinas Medical Center",
  "Avera McKennan",
  "Barnes Jewish St. Peters Hospital",
  "Beth Israel Lahey Health System (14 hospitals)",
  "Billings Clinic",
  "Brown University Health The Miriam Hospital",
  "Children's Hospital Colorado",
  "Children's Hospital of Philadelphia",
  "Children's Mercy Kansas City",
  "City of Hope National Medical Center",
  "Clara Maass Medical Center (CMMC)",
  "Cone Health",
  "Deborah Heart and Lung Center",
  "East Alabama Health",
  "Emory University Hospital Midtown",
  "Enloe Health",
  "Garden County Health Services",
  "Harbor-UCLA Medical Center",
  "Hillcrest Hospital Claremore",
  "INTEGRIS Health Miami Hospital",
  "Jefferson Einstein Montgomery Hospital",
  "LA General Medical Center",
  "LMH Health",
  "Marshall Health Network",
  "Martin Luther King Jr Community Hospital",
  "MedStar Georgetown University Hospital",
  "Memorial Community Health, Inc",
  "Michigan Medicine",
  "Montefiore Einstein",
  "MultiCare Deaconess Hospital",
  "MUSC Health",
  "New York Presbyterian Weill Cornell",
  "Newport Hospital",
  "Norman Regional Health System",
  "NYULH, Tisch Kimmel Campus - Flagship Campus",
  "Orlando Regional Medical Center",
  "OSF Saint Anthony Medical Center",
  "Poplar Bluff Regional Medical Center (affiliated with Community Health Systems)",
  "Rady Children's Hospital",
  "Redlands Community Hospital",
  "Saint Francis Health System",
  "Santiam Hospital",
  "Samaritan Health Services",
  "Stanford Health Care",
  "St. Louis Children's Hospital",
  "Sutter Medical Center Sacramento",
  "Tampa General Hospital",
  "The Queen's Medical Center",
  "The University of Kansas Health System",
  "Torrance Memorial Medical Center",
  "Tufts Medical Center",
  "UCSF Health",
  "UNC Health Rex",
  "University Medical Center New Orleans",
  "University of Miami Health System",
  "Valley Health Winchester Medical Center",
  "William Osler Health System",
  "Woodland Memorial Hospital",
  "Woodstock Hospital",
  "Other",
] as const;
